### ISSUE TITLE
Allow semver ranges and identifiers in urls

### ISSUE THREAD

**Issue by jimsimon** [denoland/website_feedback#1]
The website should be able to resolve semver symbols. Being able to use semver to dedupe dependencies is an important step towards facilitating the development of medium to large web apps using Deno. I believe some other github redirectors already support this as well.  While we could use those CDNs instead, the deno.land registry is currently the only place that exclusively lists deno modules. It may be possible to build further deduping tools once basic semver support is in place.

Some examples of what URLs would look like:
`https://deno.land/std@^0.50.0/path/mods.ts`
`https://deno.land/std@~0.50.0/path/mods.ts`
`https://deno.land/std@>=0.50.0/path/mods.ts`
`https://deno.land/std@0.49.0||^0.51.0/path/mods.ts`
`https://deno.land/std@0.49.0-0.51.0/path/mods.ts`

**Comment by dsherret** [comment]
Semvered specifiers are now possible with JSR (https://jsr.io/) and with npm specifiers. I think we can close this one.

**Comment by cowboyd** [comment]
@dsherret I might not be using the correct syntax on this one, but it appears that only a small subset of semver ranges are supported. For example if I wanted to depend on either react 18, or react 19, with npm you can use `>=18` as a specifier, or `^18 || ^19`, but I'm not finding a way to specify this with Deno.

```
 $ deno add "npm:react@>=18"
error: Failed to parse package: npm:react@>=18

Caused by:
    0: Invalid package specifier 'npm:react@>=18'
    1: Invalid specifier version requirement
    2: Unexpected character.
         >=18
         ~
```

**Comment by lucacasonato** [comment]
@cowboyd Please open an issue on denoland/deno, and not on this 5 year old closed issue :)

**Comment by cowboyd** [comment]
@lucacasonato Excellent point :) 

Here you go: https://github.com/denoland/deno/issues/28852
