### ISSUE TITLE
Support publishing to registry with an importmap

### ISSUE THREAD

**Issue by dsherret** [denoland/website_feedback#3]
It might be useful for people to publish to the registry with the import map unfurled.

For example, say the module has an import map like so:

```json
{
   "imports": {
      "fmt/": "https://deno.land/std@0.108.0/fmt/"
   }
}
```

And a TypeScript file like so:

```ts
import { red } from "fmt/colors.ts";

console.log(red("hello world"));
```

The user would be able to somehow specify "here's the import map to use for my module" to the registry (edit: nowadays, probably automatically resolved from deno.json/jsonc or perhaps this could be a GH action build step) and it would be published to the registry as:

```ts
import { red } from "https://deno.land/std@0.108.0/fmt/colors.ts";

console.log(red("hello world"));
```

**Comment by idranme** [comment]
Good idea.

**Comment by dsherret** [comment]
No longer relevant with the release of https://jsr.io

This now happens automatically on `deno publish`
