### ISSUE TITLE
Why was the source code unpublished?

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/website_feedback#34]
I understand that you want to keep deno.com to yourself, but isn't the deno.land page supposed to be the community part of this? Could you explain why you decided to hide this?

Does this affect your commitment to open-source in general?

(If this has been discussed publicly before, feel free to close this as duplicate with a link to the explanation. I couldn't find anything.)

**Comment by ry** [comment]
We decided to merge the deno.com and deno.land codebases with the goal of improving our efficiency and facilitating better code sharing. Opting for a private codebase for both allows us to manage them more effectively, but this in no way undermines the open-source nature of our broader work.

Be assured, our unwavering commitment to open source is still very much intact. Key projects like denoland/deno and denoland/rusty_v8, along with many others, are under the MIT license and remain freely available for both personal and commercial use.
