### ISSUE TITLE
Bug: can't publish new module via https://deno.com/add_module

### ISSUE THREAD

**Issue by c-antin** [denoland/website_feedback#40]
https://deno.com/add_module seems to be broken.
Tested via Chrome 114.0.5735.198

**Comment by TheYuriG** [comment]
What exactly is the issue you are having? Did you link your repository and then made a new release with an appropriate tag?

**Comment by c-antin** [comment]
Seems to work now. Yesterday it did not update the `Payload URL`.  
But without entering a `Module name` it already says "Module successfully registered!".
