### ISSUE TITLE
Possible Typo on Deno Deploy

### ISSUE THREAD

**Issue by carlrafting** [denoland/website_feedback#63]
While checking out the new design of Deno Deploy, I came across some code examples that caught my attention. I've attached a screenshot of the section on the website in question.

![Screenshot 2024-02-11 202424](https://github.com/denoland/website_feedback/assets/121248/b7309eb2-7e6a-4675-93e1-ddec646390c8)

Isn't the terminal example supposed to be something like:

```
$ deno run server.js
> Ready! Waiting for requests...
```

If not. Is this something new coming in the 2.0 release? Running deno scripts with node?

Am I missing something here 🤔, or is it just a typo?

**Comment by kt3k** [comment]
cc @josh-collinsworth

**Comment by josh-collinsworth** [comment]
Yeah that's a mistake from some copied and pasted text from an old design. Apologies for the confusion, but thanks for reporting @carlrafting! We'll update that right away.
