### ISSUE TITLE
404 links on https://deno.com/benchmarks

### ISSUE THREAD

**Issue by Jolg42** [denoland/website_feedback#66]
See https://deno.com/benchmarks

It looks like all the links to the source code are now broken on that page?

404 link: https://github.com/denoland/deno/blob/main/cli/tests/testdata/run/003_relative_import.ts
Correct link: https://github.com/denoland/deno/blob/main/tests/testdata/run/003_relative_import.ts

**Comment by kt3k** [comment]
@iuioiua Can you take a look at this?

**Comment by crowlKats** [comment]
Closing as fixed
