### ISSUE TITLE
Subhosting success stories panels are out of bounds

### ISSUE THREAD

**Issue by asiaznik** [denoland/website_feedback#72]
It appears that the panels here: https://deno.com/subhosting#case-studies
are outgrowing the container on Safari

![image](https://github.com/denoland/website_feedback/assets/1980305/7a8a0f92-61ef-4f2f-a1a3-d5e8e7940660)

**Comment by josh-collinsworth** [comment]
Thanks for reporting this. Nearly as I can tell, this was some really weird Safari bug due to a specific confluence of styles. Couldn't replicate it outside of the site, but fortunately it's fixed by explicitly setting `grid-auto-row` (which shouldn't need to be done, but idk, it's Safari).
