### ISSUE TITLE
Inconsistent deno.json `workspaces` and `workspace.members` schema in docs

### ISSUE THREAD

**Issue by cspotcode** [denoland/website_feedback#85]
I'm not sure if this is a bug or not, but I was confused by the workspaces docs:

https://docs.deno.com/runtime/fundamentals/workspaces/

1. Inconsistent examples in code blocks
2. Matrix of deno.json options says `workspace`; should say `workspaces`?

---

In one place it shows this deno.json:

```
{
  "workspace": ["./add", "./subtract"]
}
```
And in another it shows this:

```
{
  "workspace": {
    "members": ["hi"]
  }
}
```

Though it doesn't explicitly describe this `workspace.members` schema, which makes me wonder if it's a typo.

The matrix of `deno.json` options also says `workspace` instead of `workspaces`, and I'm not sure if that's a typo.

**Comment by lambtron** [comment]
hey there,
thanks for creating this issue and your patience.
the correct term is actually `workspace` :)
